// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:flutter_application_one/models/broadcast_attribute.dart';
import 'package:flutter_application_one/models/notification_data.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BroadcastAttributeAdapter());
    registerAdapter(NotificationDataAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BroadcastAttributeAdapter());
    registerAdapter(NotificationDataAdapter());
  }
}
