// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:flutter_application_one/models/broadcastAttribute.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BroadcastAttributeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BroadcastAttributeAdapter());
  }
}
